---
title: Albert blog
email: albert.aleksieiev@gmail.com
description: ''
baseurl: ''
url: ''
twitter_username: albert_keyj
github_username: albert.aleksieiev
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
